### PR TITLE
[wip] Improve logs for Docker for Mac

### PR DESCRIPTION
**Pull request by akimd**

### CODE REVIEW

**Comment by ijc** [comment]
Please stay with `vndr`. For the missing `LICENSE` files I think all that is needed is to rerun it with a newer version of `vndr`, it has been keeping those files for a very long time and works fine for other moby projects.

**Comment by akimd** [comment]
Hi @ijc.  vndr is the past already.  I'm not sure I understand why we should still be waiting to migrate.  All the other Docker components made the move already.

**Comment by ijc** [comment]
`go dep` is "the official experiment" and a "prototype" I see no reason to rush to it and to declare `vndr` as "the past" is pure hyperbole.

`vndr` is still the de facto vendoring tool used in the Moby project and in related projects (`moby`, `docker/cli`, `buildkit`, `containerd`, `runc`, `linuxkit` all continue to use `vndr` at the moment AFAICT).

Switching to `go dep` right now is premature, please drop those changes from this PR.

**Comment by akimd** [comment]
@justincormack Yes, I'm eager to see what vgo becomes, how quickly it gets adopted, etc.  Meanwhile, the traction that dep gets is quite clear however.

@ijc This is WIP.  When I feel ready to submit something, I'll tidy and remove the tag.  Meanwhile, this is a sandbox.

Cheers!

**Comment by ijc** [comment]
> This is WIP. When I feel ready to submit something, I'll tidy and remove the tag. Meanwhile, this is a sandbox.

OK. Please _remove_ (don't just revert) the `godep` commits before removing the WIP tag.

**Comment by akimd** [comment]
Obsoleted by #196.

**Pull request closed without merging**
