### PR TITLE
Go: remove the reloading from json

### PR DESCRIPTION
**Pull request by akimd**
In https://github.com/moby/hyperkit/pull/174#issuecomment-356305949 it was discussed that this feature might be unused and useless.   This PR is meant to sort this out.

### CODE REVIEW

**Comment by akimd** [comment]
I have no idea whether the use in the sample is a proof that the feature should be maintained, or something that should be removed.

**Comment by ijc** [comment]
@rn once upon a time you planned to use this in linuxkit, but I don't think that ever came to pass. Is it likely to now or shall we drop this stuff?

**Comment by rn** [comment]
drop it for now. Unlikely to use it anytime soon. But the PR failed because not all instances of `FromState`were removed

**Comment by ijc** [comment]
CI says:
```
sample/main.go:7:2: imported and not used: "encoding/json"
```

**Comment by akimd** [comment]
Thanks for the heads up!

**Comment by rn** [comment]
It would be good if you could test this *before* submitting

**Comment by akimd** [comment]
@rn Yes, sorry about this.

**Pull request merged**
