### PR TITLE
resolved formatter type error

### LINKED ISSUE #200: error: format specifies type 'ssize_t' (aka 'long') but the argument has type 'off_t' (aka 'long long')
I am getting the following errors in master. Changing the formatters to `%ll` fixes the problem. Any ideas why I am seeing this? OS 10.13.4

```
☁  hyperkit [master] make -j4
cc src/lib/firmware/bootrom.c
src/lib/firmware/bootrom.c:95:49: error: format specifies type 'ssize_t' (aka 'long') but the argument has type 'off_t' (aka 'long long')
      [-Werror,-Wformat]
                fprintf(stderr, "Invalid bootrom size %zd\n", sbuf.st_size);
                                                      ~~~     ^~~~~~~~~~~~
                                                      %lld
src/lib/firmware/bootrom.c:101:22: error: format specifies type 'ssize_t' (aka 'long') but the argument has type 'off_t' (aka 'long long')
      [-Werror,-Wformat]
                    "page size\n", sbuf.st_size);
                                   ^~~~~~~~~~~~
src/lib/firmware/bootrom.c:112:4: error: format specifies type 'ssize_t' (aka 'long') but the argument has type 'off_t' (aka 'long long')
      [-Werror,-Wformat]
                        sbuf.st_size);
                        ^~~~~~~~~~~~
3 errors generated.
make: *** [build/lib/firmware/bootrom.o] Error 1
```

```
diff --git a/src/lib/firmware/bootrom.c b/src/lib/firmware/bootrom.c
index 02cdecd..3ae2b6a 100644
--- a/src/lib/firmware/bootrom.c
+++ b/src/lib/firmware/bootrom.c
@@ -92,12 +92,12 @@ uint64_t bootrom_load(void)
         * MMIO space (e.g. APIC, HPET, MSI).
         */
        if (sbuf.st_size > MAX_BOOTROM_SIZE || sbuf.st_size < XHYVE_PAGE_SIZE) {
-               fprintf(stderr, "Invalid bootrom size %zd\n", sbuf.st_size);
+               fprintf(stderr, "Invalid bootrom size %lld\n", sbuf.st_size);
                goto done;
        }

        if (sbuf.st_size & XHYVE_PAGE_MASK) {
-               fprintf(stderr, "Bootrom size %zd is not a multiple of the "
+               fprintf(stderr, "Bootrom size %lld is not a multiple of the "
                    "page size\n", sbuf.st_size);
                goto done;
        }
@@ -108,7 +108,7 @@ uint64_t bootrom_load(void)
        ptr = vmm_mem_alloc(gpa, (size_t)sbuf.st_size);
        if (!ptr) {
                fprintf(stderr,
-                       "Failed to allocate %zd bytes of memory for bootrom\n",
+                       "Failed to allocate %lld bytes of memory for bootrom\n",
                        sbuf.st_size);
                rv = -1;
                goto done;
```

### PR DESCRIPTION
**Pull request by cmoad**
Resolves #200

### CODE REVIEW

**Comment by ijc** [comment]
Thanks. Please add a signed off by (I wonder where our bot has gotten too...) and while you are there editing the commit message please paste in the original error for the logs.

**Comment by cmoad** [comment]
@ijc I don't understand what I'm missing. I added the sign off and error message to the commit message.

**Comment by ijc** [comment]
I've added a workaround for the CI breakage in #202 which has now been merged. Please rebase onto current master to pickup the change and force push the change to your branch here. Sorry for the inconvenience.

**Comment by cmoad** [comment]
@ijc Done and done

**Comment by ijc** [comment]
Oh FFS, now something else is wrong with CI. Sorry, please bear with me.

**Comment by ijc** [comment]
#207 will hopefully fix this new one, but I'm afraid that'll mean another rebase once it is merged.

If you are getting sick and tired of this nonsense I'd be happy to carry your patch from here in #204 since it needs it anyway.

**Comment by ijc** [comment]
#207 is merged, please rebase again (sorry) or let me know if you would like me to carry the change.

**Comment by ijc** [comment]
CI (finally) green, merging. Thanks for you contribution and your patience!

**Pull request merged**
