### PR TITLE
Fix implicit conversion changes signedness errors with clang 11

### LINKED ISSUE #260: error: implicit conversion changes signedness: 'enum vm_reg_name' to 'int'
Issue #246 was not fixed by the e499d90 commit referenced in marking it closed.

I am seeing this error on the latest master (c0dd463).

```
gen src/lib/dtrace.d
cc src/lib/vmm/intel/vmcs.c
cc src/lib/vmm/intel/vmx.c
src/lib/vmm/intel/vmx.c:1368:34: error: implicit conversion changes signedness: 'enum vm_reg_name' to 'int' [-Werror,-Wsign-conversion]
        error = vmx_getreg(vmx, vcpuid, reg, &val);
                ~~~~~~~~~~              ^~~
src/lib/vmm/intel/vmx.c:1419:40: error: implicit conversion changes signedness: 'enum vm_reg_name' to 'int' [-Werror,-Wsign-conversion]
        error = vmx_getdesc(vmx, vcpuid, vis->seg_name, &vis->seg_desc);
                ~~~~~~~~~~~              ~~~~~^~~~~~~~
2 errors generated.
make: *** [build/lib/vmm/intel/vmx.o] Error 1
```

λ  sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87

λ xcodebuild -version
Xcode 11.0
Build version 11A420a

λ cc --version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### PR DESCRIPTION
**Pull request by jarrodconnolly**
Fixes #260 using example provided in comments from xhyve project.

Builds and local `make test` passes, I am not an expert in this code so needs some review.

### CODE REVIEW

**Comment by townsend2010** [comment]
It would be really nice to have this fixed :grin:  Any word on getting this reviewed and merged?

**Comment by jconnolly-kabam** [comment]
Checking in on this PR, would be great to get hyperkit building again on OSX.

**Comment by jarrodconnolly** [comment]
Checking in. It would be great to get hyperkit building again on OSX.

**Comment by djs55** [comment]
Thanks for your work on this and sorry for the delay. A fix was merged in #270 and the CI is now green again!

**Pull request closed without merging**
