### PR TITLE
Fix a small typo in README

### PR DESCRIPTION
**Pull request by jtvhk**
Corrected a small typo in the License and Copyright section.

Signed-off-by: James Hill-Khurana <hello@jameshk.com>

### CODE REVIEW

**Comment by ijc** [comment]
Thanks @jtvhk. CI is failing with:
```
# github.com/moby/hyperkit/go
../../go/src/github.com/moby/hyperkit/go/disk_test.go:19: Skip call has possible formatting directive %v
FAIL	github.com/moby/hyperkit/go [build failed]
make: *** [test] Error 2
```
Looks like `lint` has changed under us. Please rebase onto master to pickup #190.

**Comment by jtvhk** [comment]
Will do shortly, thanks!

**Comment by ijc** [comment]
@jtvhk Try this (assuming `origin` is your git remote which points at this repository, perhaps you use `upstream` or something in which case should should adjust):
```
git fetch origin
git rebase -i origin/master
```
At this point you will be presented with an editor with a bunch of lines starting `pick` with a hash and the short description, (plus some commented lines starting with `#` which you can ignore). Edit that file to contain only a single `pick` line of one of your `fix typo` commits and no `pick` of anything else. Save and exit and it should then rebase and apply only that one commit. Given the scope of your change the rebase should be clean so no need to resolve conflicts so I won't go into that here. If it _isn't_ clean or if something else goes wrong do `git rebase --abort` to go back to your initial state.

Once you have fixed your local branch then you can do `git push jtvhk +typo` (if `jtvhk` is your remote pointing to your fork, it might be `origin` in which case adjust), the `+` means "force" since your branch is not going to be a descendent of your remote branch at this point.

You can list your remotes and where they point with `git remote -v`.

**Comment by ijc** [comment]
@jtvhk do you still plan to rebase/squash this PR?

**Comment by ijc** [comment]
I'm going to close this for now. Please open a new PR with the rebased/squashed change if you have time. Thanks for your contributions so far.

**Comment by ijc** [comment]
seems I hit the wrong button last week and did not close, doing so now.

**Pull request closed without merging**
