### PR TITLE
go: don't tie the users to golang's log

### PR DESCRIPTION
**Pull request by akimd**
- define a Logger interface to gain independance.
- really use the user's logger

If preferred, I can split this in three steps.

### CODE REVIEW

**Comment by rn** [comment]
I don't think we want logrus in here and if we do it needs to be vendored.

**Comment by akimd** [comment]
The CI failure seems to be unrelated.

**Comment by djs55** [comment]
At the moment the CI is using the homebrew version of `ocaml`, which occasionally updates and exposes some breakage-- I'm fixing these problems upstream atm. I think the `was built for newer OSX version` errors are coming from the binary libs shipped with the homebrew package too.

The ideal fix for both of these issues would be to pin the package versions and build everything (including the OCaml compiler) from source -- this is what we do in `moby/vpnkit`. I'll take a look at importing the scripts from there and see if I can make use of the CI cache to speed things up.

**Comment by djs55** [comment]
@akimd to fix the CI, try rebasing on top of latest master.

**Comment by akimd** [comment]
@djs55 Thanks, it worked!

**Comment by djs55** [comment]
The logging change LGTM.

**Comment by akimd** [comment]
Thanks.  But I'm not allowed to merge.

**Pull request merged**
