### PR TITLE
Change references of OS X to macOS

### PR DESCRIPTION
**Pull request by jtvhk**
Admittedly personal preference about whether or not to call it macOS or OS X comes into play here, but I have updated the reference about the platform as a whole, not a specific version, given its new name going forward. 

Signed-off-by: James Hill-Khurana <hello@jameshk.com>

### CODE REVIEW

**Comment by jtvhk** [comment]
Whoops, I forgot to sign off on my commit as specified in `CONTRIBUTING.md`—sorry about that!

**Comment by rn** [comment]
I don't understand this rename. Apple now calls it `macOS`. `OS X` was used till 2016

**Comment by jtvhk** [comment]
@rn Ah, sorry for the confusion. Yes, I changed the reference from `OS X` to `macOS`.

**Comment by rn** [comment]
Thanks. Can you sqaush your commits and rebase to master.

**Comment by jtvhk** [comment]
Will do shortly, thanks!

**Comment by ijc** [comment]
Yes, please squash and rebase.

I'm not sure the `(formerly...)` bit is useful, practically noone who knew what OSX was is going to be confused by MacOS.

OOI why did you drop the update of the OSX In the build badge?

**Comment by jtvhk** [comment]
Whoops, still need to squash these, standby.

**Comment by ijc** [comment]
This one still needs a rebase and squash (not a merge).

**Pull request closed without merging**
