### PR TITLE
Add support for setting a bootrom in Go API

### PR DESCRIPTION
**Pull request by justincormack**
This can be used for UEFI boot for example.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by justincormack** [comment]
I have a LinuxKit patch to support UEFI ISO boot on hyperkit once this is merged.

**Comment by justincormack** [comment]
Argh, Ocaml has broken
```
type_conv.109.15.00 is not available because your system doesn't comply with ocaml-version >= "4.00.1" & ocaml-version < "4.03.0".
```

cc @djs55

**Comment by samoht** [comment]
Seems that brew updated the version of OCaml to 4.05:

```
Downloading https://homebrew.bintray.com/bottles/ocaml-4.05.0.el_capitan.bot
```

A possible fix would be to replace https://github.com/moby/hyperkit/blob/master/circle.yml#L21 by
```
opam init --yes --compiler=4.04.2
```

**Comment by djs55** [comment]
@samoht thanks -- I'll give that a go. Looking at the error message I might also try to see if I can pin a hash of `cohttp` -- maybe the problem would be fixed in the unreleased 1.0?

**Comment by djs55** [comment]
I've updated some dependencies build with OCaml 4.05. Once these are merged:

- https://github.com/ocaml/opam-repository/pull/10001
- https://github.com/ocaml/opam-repository/pull/10002

I'll make a PR to fix the CI here. Hopefully it'll work with old and new versions of OCaml.

**Comment by djs55** [comment]
@samoht I've got another one for you! https://github.com/ocaml/opam-repository/pull/10007

**Comment by samoht** [comment]
@djs55 I've merged it as well

**Comment by djs55** [comment]
Fix for the CI is in #151

**Pull request merged**
