### PR TITLE
go: Make hyperkit wrapper compilable on other OSes

### PR DESCRIPTION
**Pull request by rneugeba**
In LinuxKit we want to use the HyperKit wrapper on all supported
OSes and just error out when not running on macOS.

The previous commit (terminal handling) introduced macOS specifics
which fail to compile for Linux. This commit adds a fallback
for OSes other than macOS, which simply error out when called.

Signed-off-by: Rolf Neugebauer <rolf.neugebauer@docker.com>

### CODE REVIEW

**Comment by justincormack** [comment]
Oh I dont seem to have write access any more...

**Comment by justincormack** [comment]
Can someone give me back admin access as I am a maintainer...

**Comment by rneugeba** [comment]
@justincormack gave you back admin right (i had to request it too after the move)

**Comment by ijc25** [comment]
@rneugeba how hard would it be to either add a Linux (and others?) cross compile test to the existing `circle.yml` or to add a Linux CI (travis or something)?

**Comment by rneugeba** [comment]
@ijc25 easy: https://github.com/moby/hyperkit/pull/139

**Pull request merged**
