### PR TITLE
Go: remove uses of the lock file

### PR DESCRIPTION
**Pull request by akimd**
This is now handled by qcow-tool itself for `compact`.  It was actually not needed for `check`: it is read-only and designed to work on a live disk.

See https://github.com/mirage/ocaml-qcow/pull/106.

### CODE REVIEW

**Comment by akimd** [comment]
The failure seems unrelated to my PR.

**Comment by ijc** [comment]
> see the pinata PR ... and docker/pinata#8430.

Most of the people who might read this cannot see this internal repo, please make PR descriptions which are usable/complete with only public information.

**Comment by akimd** [comment]
I removed non public information.

**Comment by djs55** [comment]
This is a follow-on from https://github.com/moby/hyperkit/pull/173 and is safe now that the disk image itself is being locked.

Looks good to me!

**Comment by ijc** [comment]
@akimd please could you also remove the reference to Piñata from the commit message. With that LGTM too.

**Comment by akimd** [comment]
@ijc Done, sorry I missed it.

**Pull request merged**
